### ISSUE TITLE
could not parse the response returned by the baidupan server

### ISSUE THREAD

**Issue by xugui0821** [HackingBaidu/BaiduPanApi#20]
无法登陆

**Comment by xugui0821** [comment]
发错地方了，是那个百度网盘挂载的

**Comment by DDoSolitary** [comment]
这是已知问题：#17
主要原因是百度服务器返回的Cookies过期日期使用两位数年份，但是C#的HTTP客户端使用Windows的本地化设置来解析年份，这和绝大多数浏览器的行为都不同。
目前没有找到比较好的在代码中解决的方法，临时解决方案是修改系统的两位数年份的识别设置
控制面板->区域和语言->更改日期、时间和数字设置->其他设置...->日期->当键入的年份为两位数字时，将其显示为在这些年之间->把这个数字改大一些，比如改成`2039`。

**Comment by DDoSolitary** [comment]
听说百度最近加强了模拟浏览器登陆的封锁，我决定不在直接支持登陆，而是向用户请求`BDUSS`和`bdstoken`来访问百度服务器（#21）
所以这个issue就先关了

**Comment by xugui0821** [comment]
不如弄个网页框自己登录或者扫码登录，再读取cookies。

**Comment by DDoSolitary** [comment]
目前就是这么打算的 😄

**Comment by DDoSolitary** [comment]
不过目前实在是没时间来维护，可能要拖到暑假的时候了 😢
